job_username: "nikrik"
job_password: "zaq12wsx"
secret_token: "be1e7d5ba0b0ae20f9d44cce8a86d7cfb2b9de5dcc403f0f301062bc95b9136508db8ff4c68a154e51c0e09d9ff7afb9bf07733fd76670142d3dbe678f12acdb"
mail_username: "admin@insuranceshopee.com"
mail_password: "rugudwalyimigmfd"
development:
  host: "localhost:3000"
  google_api_id: "817304078239-hncrsi9lt890j4binn1meeqnut9en3uc.apps.googleusercontent.com"
  google_secret: "9n8npiu1MhWraOmZKWz5vhnT"
  facebook_api_id: "124210724437097"
  facebook_secret: "dc72c56a60e358038faa43c389c8b09a"
test:
  host: "test.local"
production:
  host: "insuranceshopee.com"
  google_api_id: "817304078239.apps.googleusercontent.com"
  google_secret: "oUk3oDLb2Z-BNICnRNtPJtAK"
  facebook_api_id: "124210724437097"
  facebook_secret: "dc72c56a60e358038faa43c389c8b09a"

