job_username: "nikrik"
job_password: "zaq12wsx"
secret_token: "be1e7d5ba0b0ae20f9d44cce8a86d7cfb2b9de5dcc403f0f301062bc95b9136508db8ff4c68a154e51c0e09d9ff7afb9bf07733fd76670142d3dbe678f12acdb"
mail_username: "rikhiljain"
mail_password: "gisnvfegpvjeienb"
development:
  host: "localhost:3000"
test:
  host: "test.local"
production:
  host: "oyeinsurance.com"