CREATE TABLE IF NOT EXISTS `motor_searches` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `new_policy` tinyint(1) DEFAULT NULL,
  `policy_exp_date` date DEFAULT NULL,
  `year_of_manufacture` year(4) DEFAULT NULL,
  `idv_chart_id` int(11) DEFAULT NULL,
  `register_type` char(1) NOT NULL,
  `register_date` date DEFAULT NULL,
  `rto_id` int(11) NOT NULL,
  `has_claim` tinyint(1) DEFAULT NULL,
  `ncb` int(11) DEFAULT NULL,
  `elec_acc` int(11) DEFAULT NULL,
  `non_elec_acc` int(11) DEFAULT NULL,
  `cng_type` varchar(20) DEFAULT NULL,
  `cng_value` int(11) DEFAULT NULL,
  `passenger_coverage_amt` int(11) DEFAULT NULL,
  `has_anti_theft` tinyint(1) DEFAULT NULL,
  `has_full_cover` tinyint(1) DEFAULT NULL,
  `is_aai_member` tinyint(1) DEFAULT NULL,
  `email_id` varchar(50) DEFAULT NULL,
  `mobile_number` int(11) DEFAULT NULL,
  `address` varchar(255) DEFAULT NULL,
  `company_name` varchar(20) DEFAULT NULL,
  `final_premium` int(11) DEFAULT NULL,
  `created_at` datetime NOT NULL,
  PRIMARY KEY (`id`)
) ;